---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/visitors
  label: Visitors
  create: all
  match: "**/*"
- type: directory
  path: content/teaching
  label: Teaching
  create: all
  match: "**/*"
- type: directory
  path: content/research
  label: Research
  create: all
  match: "**/*"
- type: directory
  path: content/publications
  label: Publications
  create: all
  match: "**/*"
- type: directory
  path: content/programs
  label: Programs
  create: all
  match: "**/*"
- type: directory
  path: content/people
  label: People
  create: all
  match: "**/*"
- type: directory
  path: content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: content/management
  label: Management
  create: all
  match: "**/*"
- type: directory
  path: content/join-us
  label: Join us
  create: all
  match: "**/*"
- type: directory
  path: content/gallery
  label: Gallery
  create: all
  match: "**/*"
- type: directory
  path: content/events
  label: Events
  create: all
  match: "**/*"
- type: directory
  path: content/credits
  label: Credits
  create: all
  match: "**/*"
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
- type: directory
  path: content/about-us
  label: About us
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
